# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
