# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing_users', '0002_auto_20160506_1426'),
        ('managing_users', '0002_useraddress_name'),
    ]

    operations = [
    ]
