# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-12-07 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managing_users', '0003_merge'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='nflmuser',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='customization',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
