# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-12-07 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managing_users', '0005_remove_customization_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
