# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-14 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_users', '0006_auto_20161207_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
