# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-02-12 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_users', '0008_howtousevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howtousevideo',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
