# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-02-12 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_users', '0009_auto_20170212_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howtousevideo',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
