# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing_users', '0011_auto_20170212_0846'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='nflmuser',
            managers=[
            ],
        ),
    ]
