# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateBankingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=30)),
                ('account_no', models.BigIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=20)),
                ('IFSC_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.URLField(blank=True)),
                ('successful_usage_count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=20, unique=True)),
                ('absolute_discount', models.BooleanField(default=False, help_text='Check this if discount offered is Absolute Amount.')),
                ('cart_discount', models.BooleanField(default=True, help_text='Check this if discount to be offered is on total cart amount.')),
                ('coupon_amount', models.IntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('minimum_spend', models.IntegerField(default=0)),
                ('maximum_spend', models.IntegerField(default=0)),
                ('exclude_sale_items', models.BooleanField(default=False, help_text='Check this box if coupon should not apply to items on sale')),
                ('usage_limit_per_coupon', models.IntegerField(default=0)),
                ('usage_limit_per_user', models.IntegerField(default=0)),
                ('usage_count', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('products_excluded', models.ManyToManyField(blank=True, related_name='products_excluded_in_coupon', to='products.Product')),
                ('products_included', models.ManyToManyField(blank=True, related_name='products_included_in_coupon', to='products.Product')),
                ('users_restricted', models.ManyToManyField(blank=True, related_name='users_restricted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CouponUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_usage_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrals_added_count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.Coupon')),
                ('referral_list', models.ManyToManyField(blank=True, related_name='user_referral_list', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_referral', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='affiliateprogram',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.Coupon'),
        ),
        migrations.AddField(
            model_name='affiliateprogram',
            name='coupon_used_users',
            field=models.ManyToManyField(blank=True, related_name='affiliate_coupon_used_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliateprogram',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliatebankingdetails',
            name='affiliate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_banking_details', to='marketing.AffiliateProgram'),
        ),
    ]
