# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 17:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managing_users', '0001_initial'),
        ('carts', '0001_initial'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='ABC', max_length=120, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('guest_customer', models.BooleanField(default=False)),
                ('guest_email', models.EmailField(blank=True, max_length=30, null=True)),
                ('coupon_discount', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Completed', 'Completed')], default='Started', max_length=120)),
                ('payment_method', models.CharField(choices=[('CCAvenue', 'CCAvenue'), ('Paytm', 'Paytm')], default='CCAvenue', max_length=20)),
                ('gift_wrap', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('final_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('billing_address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='managing_users.UserAddress')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.Cart')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.Coupon')),
                ('shipping_address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='managing_users.UserAddress')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('line_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
