# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160427_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='longurl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='mac',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_request_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='shorturl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
