# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20160428_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CCAvenue', 'CCAvenue'), ('Instamojo', 'Instamojo')], default='CCAvenue', max_length=20),
        ),
    ]
