# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20160504_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.IntegerField(default=0),
        ),
    ]
