# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-02-12 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170114_2023'),
        ('blog', '0003_auto_20170114_1938'),
    ]

    operations = [
    ]
