# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='occasional',
            field=models.BooleanField(default=False),
        ),
    ]
