# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_occasional'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='alt_text',
            field=models.CharField(default='alt_text', max_length=30),
        ),
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/tags/'),
        ),
    ]
