# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-14 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_custom_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknotification',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
