# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_stocknotification_date_added'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
