# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10, null=True)),
                ('img1', models.ImageField(height_field=120, null=True, upload_to='', width_field=120)),
                ('alt_1', models.CharField(max_length=20, null=True)),
                ('img2', models.ImageField(height_field=120, null=True, upload_to='', width_field=120)),
                ('alt_2', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
