# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pairs',
            options={'verbose_name': 'VotingPair', 'verbose_name_plural': 'VotingPairs'},
        ),
        migrations.AlterField(
            model_name='pairs',
            name='img1',
            field=models.ImageField(null=True, upload_to='voting/images'),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='img2',
            field=models.ImageField(null=True, upload_to='voting/images'),
        ),
    ]
