# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20170613_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairs',
            name='s1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pairs',
            name='s2',
            field=models.IntegerField(default=0),
        ),
    ]
