# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20170613_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pairs',
            options={'ordering': ['pid'], 'verbose_name': 'VotingPair', 'verbose_name_plural': 'VotingPairs'},
        ),
        migrations.AlterField(
            model_name='pairs',
            name='pid',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
