# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20170614_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairs',
            name='pid',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
