# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20170614_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairs',
            name='a1',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pairs',
            name='a2',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
